services:
  backend:
    image: tab-keno-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    image: tab-keno-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_TABO_BACKEND_WEBSOCKET: ws://localhost:8080/api/v1/ws
      VITE_REDIRECT_URI: http://localhost:80/redirect
      VITE_CLIENT_ID: ${DISCORD_APP_CLIENT_ID}
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
    driver: local