definitions:
  api.APIError:
    properties:
      message:
        type: string
    type: object
  api.CheckCardResponse:
    properties:
      amount:
        type: integer
    type: object
  api.PickRequest:
    properties:
      number_games:
        type: integer
      picks:
        items:
          type: integer
        type: array
      picks_per_game:
        type: integer
      price_per_game:
        type: integer
    type: object
  api.PickResponse:
    properties:
      card_id:
        type: integer
      last_game_num:
        type: integer
      selection:
        items:
          type: integer
        type: array
      start_game_num:
        type: integer
    type: object
  models.Message:
    properties:
      body: {}
      type:
        description: The message type
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for TAB Keno API.
  title: TAB Keno API
  version: "1.0"
paths:
  /api/v1/check/{card_id}:
    get:
      description: Check your card to see if you won and claim your wins.
      parameters:
      - description: Card ID
        in: path
        name: card_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CheckCardResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.APIError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Check your card to see if you won
      tags:
      - cards
  /api/v1/picks:
    post:
      consumes:
      - application/json
      description: |-
        Give us your numbers so you can enjoy the number of games you specify. There are some rules:
        - You can only pick numbers between `1` and `80`.
        - You can only pick `1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 40` numbers per game.
        - You can only play `1, 2, 3, 4, 5, 10, 20, 50, 100` number of games.
      parameters:
      - description: Your picks for the next selected games
        in: body
        name: picks
        required: true
        schema:
          $ref: '#/definitions/api.PickRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.PickResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.APIError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Place your picks for the next Keno game
      tags:
      - picks
  /api/v1/ws:
    get:
      description: When a game is calculated and started, this endpoint will stream
        the game to the client. This will include all the picks which the client will
        have to display over 1.5 minutes for the proper effect.
      parameters:
      - description: 'Connection: Upgrade'
        in: header
        name: Connection
        required: true
        type: string
      - description: 'Upgrade: websocket'
        in: header
        name: Upgrade
        required: true
        type: string
      - description: 'Sec-Websocket-Version: 13'
        in: header
        name: Sec-Websocket-Version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.APIError'
      summary: Stream the current game
      tags:
      - games
swagger: "2.0"
